### ISSUE TITLE
How to install it on my linux server?

### ISSUE THREAD

**Issue by wangtongze** [martinp/ifconfigd#5]
How to install it on my linux server? This is my site ip.accchina.pw but it has a lot of questions, do you know how to fix it?

**Comment by iamtew** [comment]
It's a fairly simple procedure. Install Go and setup your environment, instructions here: https://golang.org/doc/install

The following steps should be sufficient to get it downloaded, compiled and started:
```
go get github.com/martinp/ifconfig
cd $GOPATH/src/github.com/martinp/ifconfig
make
./bin/ifconfig
```

Now it should be up and running and listening on port 8080. Good luck!

**Comment by martinp** [comment]
The project has a standard go project layout, so you should be able to use `go get` like this:

`go get github.com/martinp/ifconfigd`

Then it will be compiled and installed into `$GOPATH/bin/ifconfigd`.
