### ISSUE TITLE
Difference between X-Real-IP and X-Ifconfig-IP?

### ISSUE THREAD

**Issue by elyscape** [martinp/ifconfigd#9]
Among other things, the [ifconfig.co][http://ifconfig.co/] page shows commands for getting the values of `X-Real-IP` and `X-Ifconfig-IP`, but it doesn't indicate what the difference between them is, if any. Is there a difference between these two values? If so, what is it?

**Comment by martinp** [comment]
There is no difference. X-Real-IP is more of an "internal" header. It's used when there's an reverse proxy in front of ifconfigd to pass the real remote IP to ifconfigd.
